version: '3.9'

services:
    db_postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: 'teste'
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080